name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if it's the backend module
        run: echo "IS_BACKEND=true" >> $GITHUB_ENV
        if: startsWith(github.event_name, 'push') && contains(github.event.head_commit.modified, 'backend/')

      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode verify
